# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Joint Trajectory Controllers -------------------------------
arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - shoulder_p_joint
    - shoulder_y_joint
    - elbow_joint
    - wrist_y_joint
    - wrist_p_joint
    - wrist_r_joint
  gains:
    shoulder_p_joint: {p: 100.0, i: 0.01, d: 10.0}
    shoulder_y_joint: {p: 100.0, i: 0.01, d: 10.0}
    elbow_joint:      {p: 100.0, i: 0.01, d: 10.0}
    wrist_y_joint:    {p: 100.0, i: 0.01, d: 10.0}
    wrist_p_joint:    {p: 100.0, i: 0.01, d: 10.0}
    wrist_r_joint:    {p: 100.0, i: 0.01, d: 10.0}
  constraints:
    trajectory: 5.0
    stopped_velocity_tolerance: 0.1
    shoulder_p_joint:
      trajectory: 0.2
      goal: 0.2
    shoulder_y_joint:
      trajectory: 0.2
      goal: 0.2
    elbow_joint:
      trajectory: 0.2
      goal: 0.2
    wrist_y_joint:
      trajectory: 0.2
      goal: 0.2
    wrist_p_joint:
      trajectory: 0.2
      goal: 0.2
    wrist_r_joint:
      trajectory: 0.2
      goal: 0.2

lifter_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - knee_joint
    - ankle_joint
  gains:
    knee_joint:  {p: 100.0, i: 0.01, d: 10.0}
    ankle_joint: {p: 100.0, i: 0.01, d: 10.0}
  constraints:
    trajectory: 5.0
    stopped_velocity_tolerance: 0.1
    knee_joint:
      trajectory: 0.2
      goal: 0.2
    ankle_joint:
      trajectory: 0.2
      goal: 0.2

hand_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - r_thumb_joint
  gains:
    r_thumb_joint:     {p: 10.0, i: 0.01, d: 1.0}
  constraints:
    trajectory: 5.0
    stopped_velocity_tolerance: 0.1
    r_thumb_joint:
      trajectory: 0.2
      goal: 0.2

robot_interface_controllers: ['arm', 'lifter']
